import Details from "./Details"
import Home from "./Home"
import CommentSection from "./CommentSection"
import Landing from "./Landing"
import Profile from "./Profile"
import DM from "./DM"
import Conversation from "./Conversation"
import AddPost from "./AddPost"
import Settings from "./Settings"
import ChangePersonalInf from "./ChangePersonalInf"
import SearchScreen from "./SearchScreen"
import SignUpScreen from "./SignUpScreen"
import EventsFeed from "./EventsFeed"
import Followers from "./Followers"

export { Details, Home, Followers, CommentSection, EventsFeed, Landing, Profile, DM, Conversation, AddPost, Settings, ChangePersonalInf, SearchScreen, SignUpScreen }